# Generated by Django 4.2.7 on 2025-07-01 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0002_alter_nivel_codigo_alter_nivel_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='central',
            name='estado',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='homologacion',
            name='tipo',
            field=models.CharField(choices=[('1', 'Numérico'), ('2', 'Booleano')], default='1', max_length=50),
        ),
        migrations.AddField(
            model_name='nivel',
            name='estado',
            field=models.BooleanField(default=True),
        ),
    ]
