# Generated by Django 4.2.7 on 2025-07-01 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0004_scadatemporal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scadatemporal',
            name='cabecera_cmd',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='scadatemporal',
            name='id_scada',
            field=models.CharField(max_length=50),
        ),
    ]
