# Generated by Django 4.2.7 on 2025-07-06 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0005_alter_scadatemporal_cabecera_cmd_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scadatemporal',
            name='timestamp_utc',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scadatemporal',
            name='tipo',
            field=models.CharField(choices=[('1', 'extraido'), ('2', 'extrapolado')], default='1', max_length=50),
        ),
    ]
