# Generated by Django 4.2.7 on 2025-07-08 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0006_scadatemporal_timestamp_utc_scadatemporal_tipo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ETLProcessState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('etapa', models.CharField(choices=[('importar', 'Importar'), ('completar', 'Completar'), ('exportar', 'Exportar'), ('comparar', 'Comparar')], max_length=20)),
                ('dia_actual', models.DateField()),
                ('completado', models.BooleanField(default=False)),
                ('actualizado', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Parametro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('valor', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Parámetros',
            },
        ),
    ]
