# Generated by Django 4.2.7 on 2025-07-09 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0007_etlprocessstate_parametro'),
    ]

    operations = [
        migrations.CreateModel(
            name='ETLProcessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('etapa', models.CharField(max_length=20)),
                ('inicio', models.DateTimeField(auto_now_add=True)),
                ('fin', models.DateTimeField(blank=True, null=True)),
                ('exito', models.BooleanField(default=False)),
                ('mensaje', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='etlprocessstate',
            name='en_ejecucion',
            field=models.BooleanField(default=False),
        ),
    ]
