# Generated by Django 4.2.7 on 2025-07-24 17:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('master', '0008_etlprocesslog_etlprocessstate_en_ejecucion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acceso_usuarios', models.BooleanField(default=False)),
                ('acceso_proceso_etl', models.BooleanField(default=False)),
                ('acceso_sensores', models.BooleanField(default=False)),
                ('acceso_configuracion', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
