# Generated by Django 4.2.7 on 2025-07-24 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0009_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='bloqueado',
            field=models.BooleanField(default=False),
        ),
    ]
