# Generated by Django 4.2.7 on 2025-08-17 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0010_profile_bloqueado'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='intentos',
            field=models.IntegerField(default=0),
        ),
    ]
