# Generated by Django 4.2.7 on 2025-08-17 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0011_profile_intentos'),
    ]

    operations = [
        migrations.CreateModel(
            name='ETLProcessLogCron',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora', models.DateTimeField()),
                ('etapa', models.CharField(max_length=20)),
                ('inicio', models.DateTimeField(auto_now_add=True)),
                ('fin', models.DateTimeField(blank=True, null=True)),
                ('exito', models.BooleanField(default=False)),
                ('mensaje', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ETLProcessStateCron',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora_inicio', models.DateTimeField()),
                ('fecha_hora_fin', models.DateTimeField()),
                ('etapa', models.CharField(choices=[('importar', 'Importar'), ('completar', 'Completar'), ('exportar', 'Exportar'), ('comparar', 'Comparar')], max_length=20)),
                ('dia', models.DateField()),
                ('completado', models.BooleanField(default=False)),
                ('en_ejecucion', models.BooleanField(default=False)),
                ('actualizado', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
