# Generated by Django 4.2.7 on 2025-08-18 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0012_etlprocesslogcron_etlprocessstatecron'),
    ]

    operations = [
        migrations.AddField(
            model_name='etlprocesslogcron',
            name='registros',
            field=models.IntegerField(default=0),
        ),
    ]
