# Generated by Django 4.2.7 on 2025-08-18 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0013_etlprocesslogcron_registros'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='etlprocesslogcron',
            name='registros',
        ),
        migrations.AddField(
            model_name='etlprocessstatecron',
            name='registros',
            field=models.IntegerField(default=0),
        ),
    ]
