# Generated by Django 4.2.7 on 2025-08-18 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0014_remove_etlprocesslogcron_registros_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='etlprocessstatecron',
            name='etapa',
        ),
    ]
