# Generated by Django 4.2.7 on 2025-08-18 05:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0015_remove_etlprocessstatecron_etapa'),
    ]

    operations = [
        migrations.AddField(
            model_name='etlprocesslogcron',
            name='proceso',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='master.etlprocessstatecron'),
            preserve_default=False,
        ),
    ]
